#! /bin/sh

uid=$1
proglist="magick identify pdftoppm pdflatex"

rm -rf tex/staging/$uid
mkdir tex/staging/$uid
cd tex/staging/$uid

hash $proglist &> /dev/null

if [ $? -eq 1 ]; then
  echo -e "Could not locate the following program(s):\n" > $uid.error
  for p in $proglist; do
    hash "$p" &> /dev/null || echo "$p" >> $uid.error
  done
  echo -e "\nPlease ensure they are installed and available in the system path." >> $uid.error
  cp ../../failed.png $uid.png
  exit 1
fi

echo -e "\\documentclass[preview, border=10pt, 12pt]{standalone}\n\\\IfFileExists{eggs.sty}{\\usepackage{eggs}}{}" > $uid.tex

if [ -f "../../preamble/$uid.tex" ]; then
    cat ../../preamble/$uid.tex >> $uid.tex
else
    cat ../../preamble/default/default.tex >> $uid.tex
fi

echo -e "\n\\\begin{document}" >> $uid.tex
cat ../../inputs/$uid.tmp >> $uid.tex
echo -e "\n\\\end{document}" >> $uid.tex

timeout 60 pdflatex -no-shell-escape -interaction=nonstopmode -cnf-line 'openin_any=r' $uid.tex > ../../log/texout.log

if [ $? -eq 124 ]; then
    echo "Compilation timed out!" > $uid.error
    cp ../../failed.png $uid.png
    exit 1
fi

if [ -f $uid.pdf ]; then
    timeout 60 pdftoppm $uid.pdf $uid -r 600 -png -singlefile

    if [ $? -eq 124 ]; then
        echo "Image conversion timed out!" > $uid.error
        cp ../../failed.png $uid.png
        exit 1
    elif [ `stat -c%s $uid.png` -gt 8000000 ]; then
        echo "Output image too large!" > $uid.error
        cp ../../failed.png $uid.png
        exit 1
    fi
else
    grep -A 10 "^!" -m 1 $uid.log > $uid.error
    cp ../../failed.png $uid.png
    exit 1
fi

if grep -q "^!" $uid.log; then
    grep -A 10 "^!" -m 1 $uid.log > $uid.error
fi

width=`identify -ping -format "%w" $uid.png`
minwidth=1000

magick $uid.png -shave 1x1 $uid.png

if [ $width -lt $minwidth ]; then
    timeout 60 magick $uid.png -background transparent -extent ${minwidth}x $uid.png
fi

